### ISSUE TITLE
Install on Capacitor 4

### ISSUE THREAD

**Issue by mh4ck** [virusv/capacitor-appmetrica-plugin#2]
Hi, i would be so gratefull if you can update it to work with Capacitor 4. Or maybe help me get App Metrica run in my application. 
I am very uncomfortable with Java and also capacitor. :-/

**Comment by virusv** [comment]
> Hi, i would be so gratefull if you can update it to work with Capacitor 4. Or maybe help me get App Metrica run in my application. I am very uncomfortable with Java and also capacitor. :-/

Hi try to install the new version

`npm install capacitor-appmetrica-plugin@^3.0.0`
